# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - general-service

on:
  push:
    branches:
      - main
      - fixbug
  pull_request:
    types:
      - closed
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install
      
      - name: Run tests
        if: ${{ job.status == 'success' }}
        run: mvn test

      - name: Upload artifact for deployment job
        if: ${{ job.status == 'success' }}
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        if: ${{ job.status == 'success' }}
        run: mvn test

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        if: ${{ job.status == 'success' }}
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'general-service'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4D0F881AE8D8426E9BFF0FE0C46C911D }}
          package: '*.jar'
      
      - name: Delete branch after deployment
        if: ${{ job.status == 'success' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Delete branch after successful deployment'
          branch: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
